REPO_TAGLINE: Optimization • modeling • algorithms
ASSETS_DIR: .github/readme
CTA_TEXT: Access the full course website
THEME: peace
SITE_URL: https://academic-codex.github.io/SME0610-Programacao-Matematica

BG_1: "#071A12"
BG_2: "#123D2E"
TEXT_MAIN: "#E9FFF6"
TEXT_MUTED: "#BCE7D6"
ACCENT: "#10B981"
CARD_RADIUS: "18"